name: amnano
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - colorlog
  - scipy
  - shapely
  - h5py
  - kwant
  - tqdm
  - seaborn
  - pytables
  - drawarrow
