# Static variables for simulating cond-vs-L in the cluster

# Fixed variables for the simulation batch
Nx          = 5        # Number of sites along x
Ny          = 5        # Number of sites along y
r           = 1.3      # Nearest-neighbour cutoff distance
t           = 1        # Hopping
mu_leads    = 1        # Chemical potential at the leads
Ef          = [0.0, 0.04]   # Fermi energy
flux_max    = 1        # Max flux
flux_min    = 0        # Min flux
flux_L      = 100      # NUmber of flux points
K_onsite    = 0.0      # Onsite disorder
K_hopp      = 0.0      # Hopping disorder


# Changing variables for the simulation batch
Nsamples   = 300
width      = [0.0001, 0.02, 0.05, 0.1]
Nz_max      = 200
Nz_min      = 30
Nz_L        = 10



