# Static variables for simulating cond-vs-N in the cluster

# Fixed variables for the simulation batch
Nz          = 200      # Number of sites along x
r           = 1.3      # Nearest-neighbour cutoff distance
t           = 1        # Hopping
mu_leads    = -1       # Chemical potential at the leads
Ef          = 0.02     # Fermi energy
flux_max    = 1        # Max flux
flux_min    = 0.4      # Min flux
flux_L      = 200      # Number of flux points
K_onsite    = 1.0      # Onsite disorder
width       = 0.1      # Amorphicity


# Changing variables for the simulation batch
Nsamples   = 100      # Number of realizations
N          = [16, 14, 12, 10, 8]  # Cross section linear size



