# Static variables for simulating cond-vs-N in the cluster

# Fixed variables for the simulation batch
Nz          = 150      # Number of sites along x
r           = 1.3      # Nearest-neighbour cutoff distance
t           = 1        # Hopping
Ef          = 0.0     # Fermi energy
w0          = 0.00000001
wf          = 0.8
wN          = 20
num_moments = 5000
num_vecs    = 5

# Changing variables for the simulation batch
Nsamples   = 20                   # Number of realizations
N          = [15, 13, 11, 9, 7]   # Cross section linear size


